nameOverride:
fullnameOverride: ""
imagesPullSecret: 
imagesPullPolicy: Always
namespace: rbacs


rbaccore:
  enabled: true
  image:
    repository: devavaxiaregistry.azurecr.io/rbaccore
    tag: "1.0.1"
  containerPort: 5002
  replicaCount: 1
  persistence:
    enabled: false
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass:
    accessMode: ReadWriteOnce
    size: 1Gi
    imagesPath: /usr/src/app/uploads
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 1
    #   memory: 1000Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  env:
    - name: RB_CLIENT_KEY
      value: "CKKEYRBCL"
    - name: ACT_KEY
      value: "CKACTRB"
    - name: RFT_KEY
      value: "CKRFTRB"
    - name: APP_CLIENT_KEY
      value: "CKKEYAPPCL"
    - name: APP_ACT_KEY
      value: "CKACTAPP"            
    - name: APP_RFT_KEY
      value: "CKRFTAPP"
    - name: BOND
      value: "r££rt?xt"
    - name: DB_HOST
      value: "mca-ref-mysql"
    - name: DB_PORT
      value: "3306"
    - name: DB_USER
      value: "rbacuser"
    - name: DB_PASS
      value: "dc0a57b1"
    - name: DB_DATABASE
      value: "avx_mca_rbac"
    - name: CORE_MODE
      value: PROD
    - name: PORT
      value: 5002
                    
  service:
    type: "ClusterIP"
    port: 80


ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  host: rbacs.avaxia-dev.avaxia-group.com
  paths: 
    rbaccore: /api/jrbac/?(.*)

mysql:
  enabled: true
  useStatefulSet: true
  auth:
    rootUser: root
    enabled: true
    rootPassword: "Avaxia&2021"
  
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  resources:  
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi
  persistence:
    size: 8Gi
  #initdbScriptsConfigMap: mysql-configmap
  
     


