apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: full-access
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: avaxibot-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-access
subjects:
- kind: ServiceAccount
  name: avaxibot
  namespace: jenkins